---
title: "Matrices de distances"
author: "Guyliann Engels & Philippe Grosjean"
description: "**SDD II Module 5** Application des concepts liés aux matrices de distances."
tutorial:
  id: "B05La_distance_matrix"
  version: 1.0.0
output: 
  learnr::tutorial:
    progressive: true
runtime: shiny_prerendered
---

```{r setup, include=FALSE}
BioDataScience2::learnr_setup()
SciViews::R()
```

```{r, echo=FALSE}
BioDataScience2::learnr_banner()
```

```{r, context="server"}
BioDataScience2::learnr_server(input, output, session)
```

----

**Ce tutoriel est encore sous sa première version, il est en cours de mise à jour.**

## Objectifs

- TODO

## Choix de l'indice

Lors de la réalisation d'une matrice de distance, vous devez choisir l'indice le plus adapté

```{r qu_indice_noscore}
quiz(
  question("Dans un tableau de dénombrement d'espèces, vous souhaitez réaliser un matrice de distance avec l'indice le plus adapté. Quel indice choississez vous ? (plusieurs réponses peuvent être sélectionnés)",
           answer("Indice de Bray-Curtis", correct = TRUE),
           answer("Indice de Canberra", correct = TRUE),
           answer("Distance Euclidienne"),
           answer("Indice de Manhattan"), 
          allow_retry = TRUE),
  question("Dans un tableau de dénombrement d'espèces, vous souhaitez réaliser un matrice de distance avec l'indice le plus adapté. Quel indice choississez vous si vous souhaitez mettre en avant les espèces rares ? (plusieurs réponses peuvent être sélectionnés)",
           answer("Indice de Bray-Curtis"),
           answer("Indice de Canberra", correct = TRUE),
           answer("Distance Euclidienne"),
           answer("Indice de Manhattan"), 
          allow_retry = TRUE),
  question("Dans un tableau relatif à des mesures environnementales, vous souhaitez réaliser un matrice de distance avec l'indice le plus adapté. Quel indice choississez vous ? (plusieurs réponses peuvent être sélectionnés)",
           answer("Indice de Bray-Curtis"),
           answer("Indice de Canberra"),
           answer("Distance Euclidienne", correct = TRUE),
           answer("Indice de Manhattan", correct = TRUE), 
          allow_retry = TRUE)
)
```


## Conclusion

Vous venez de terminer votre séance d'exercice.

```{r comm_noscore, echo=FALSE}
question_text(
  "Laissez-nous vos impressions sur ce learnr",
  answer("", TRUE, message = "Pas de commentaires... C'est bien aussi."),
  incorrect = "Vos commentaires sont enregistrés.",
  placeholder = "Entrez vos commentaires ici...",
  allow_retry = TRUE
)
```
